spring:
  application:
    name: playground

  datasource:
    username: pguser
    password: pgpassword
    url: jdbc:postgresql://localhost:5432/playground
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmquser
    password: rabbitmqpassword
    listener:
      simple:
        observation-enabled: true
    template:
      observation-enabled: true
